// Generated by gencpp from file test_prog_c/AddTwoInts.msg
// DO NOT EDIT!


#ifndef TEST_PROG_C_MESSAGE_ADDTWOINTS_H
#define TEST_PROG_C_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <test_prog_c/AddTwoIntsRequest.h>
#include <test_prog_c/AddTwoIntsResponse.h>


namespace test_prog_c
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace test_prog_c


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test_prog_c::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::test_prog_c::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::test_prog_c::AddTwoInts > {
  static const char* value()
  {
    return "test_prog_c/AddTwoInts";
  }

  static const char* value(const ::test_prog_c::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::test_prog_c::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::test_prog_c::AddTwoInts > 
template<>
struct MD5Sum< ::test_prog_c::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test_prog_c::AddTwoInts >::value();
  }
  static const char* value(const ::test_prog_c::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_prog_c::AddTwoIntsRequest> should match 
// service_traits::DataType< ::test_prog_c::AddTwoInts > 
template<>
struct DataType< ::test_prog_c::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::test_prog_c::AddTwoInts >::value();
  }
  static const char* value(const ::test_prog_c::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test_prog_c::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::test_prog_c::AddTwoInts > 
template<>
struct MD5Sum< ::test_prog_c::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test_prog_c::AddTwoInts >::value();
  }
  static const char* value(const ::test_prog_c::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_prog_c::AddTwoIntsResponse> should match 
// service_traits::DataType< ::test_prog_c::AddTwoInts > 
template<>
struct DataType< ::test_prog_c::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::test_prog_c::AddTwoInts >::value();
  }
  static const char* value(const ::test_prog_c::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_PROG_C_MESSAGE_ADDTWOINTS_H
