#!/bin/bash

#run roscore et les autres nodes
roscore &
rosrun turtlesim turtlesim_node &
#on change la couleur du pinceau
echo Calibrage pinceau 

rosservice call /turtle1/set_pen '2' '245' '245' '10' 'off'

#la figure square est en cours

rosrun turtlesim_cleaner2 ultimatesquare.py
