(cl:defpackage TP2-srv
  (:use )
  (:export
   "ANNOTATEDPOSE"
   "<ANNOTATEDPOSE-REQUEST>"
   "ANNOTATEDPOSE-REQUEST"
   "<ANNOTATEDPOSE-RESPONSE>"
   "ANNOTATEDPOSE-RESPONSE"
   "STORECURRENTPOSE"
   "<STORECURRENTPOSE-REQUEST>"
   "STORECURRENTPOSE-REQUEST"
   "<STORECURRENTPOSE-RESPONSE>"
   "STORECURRENTPOSE-RESPONSE"
  ))

