// Generated by gencpp from file tp2/AnnotatedPose.msg
// DO NOT EDIT!


#ifndef TP2_MESSAGE_ANNOTATEDPOSE_H
#define TP2_MESSAGE_ANNOTATEDPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace tp2
{
template <class ContainerAllocator>
struct AnnotatedPose_
{
  typedef AnnotatedPose_<ContainerAllocator> Type;

  AnnotatedPose_()
    : pose()
    , name()  {
    }
  AnnotatedPose_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::tp2::AnnotatedPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tp2::AnnotatedPose_<ContainerAllocator> const> ConstPtr;

}; // struct AnnotatedPose_

typedef ::tp2::AnnotatedPose_<std::allocator<void> > AnnotatedPose;

typedef boost::shared_ptr< ::tp2::AnnotatedPose > AnnotatedPosePtr;
typedef boost::shared_ptr< ::tp2::AnnotatedPose const> AnnotatedPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tp2::AnnotatedPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tp2::AnnotatedPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tp2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tp2': ['/home/seb/catkin_ws/src/tp2/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tp2::AnnotatedPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tp2::AnnotatedPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tp2::AnnotatedPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tp2::AnnotatedPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tp2::AnnotatedPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tp2::AnnotatedPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tp2::AnnotatedPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f716db42957c7b57682e1bb8a22eae4a";
  }

  static const char* value(const ::tp2::AnnotatedPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf716db42957c7b57ULL;
  static const uint64_t static_value2 = 0x682e1bb8a22eae4aULL;
};

template<class ContainerAllocator>
struct DataType< ::tp2::AnnotatedPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tp2/AnnotatedPose";
  }

  static const char* value(const ::tp2::AnnotatedPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tp2::AnnotatedPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose\n\
string name\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::tp2::AnnotatedPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tp2::AnnotatedPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AnnotatedPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tp2::AnnotatedPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tp2::AnnotatedPose_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TP2_MESSAGE_ANNOTATEDPOSE_H
