// Generated by gencpp from file TP2/AnnotatedPose.msg
// DO NOT EDIT!


#ifndef TP2_MESSAGE_ANNOTATEDPOSE_H
#define TP2_MESSAGE_ANNOTATEDPOSE_H

#include <ros/service_traits.h>


#include <TP2/AnnotatedPoseRequest.h>
#include <TP2/AnnotatedPoseResponse.h>


namespace TP2
{

struct AnnotatedPose
{

typedef AnnotatedPoseRequest Request;
typedef AnnotatedPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AnnotatedPose
} // namespace TP2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::TP2::AnnotatedPose > {
  static const char* value()
  {
    return "177d54286ddeee12eba514054bddffd5";
  }

  static const char* value(const ::TP2::AnnotatedPose&) { return value(); }
};

template<>
struct DataType< ::TP2::AnnotatedPose > {
  static const char* value()
  {
    return "TP2/AnnotatedPose";
  }

  static const char* value(const ::TP2::AnnotatedPose&) { return value(); }
};


// service_traits::MD5Sum< ::TP2::AnnotatedPoseRequest> should match 
// service_traits::MD5Sum< ::TP2::AnnotatedPose > 
template<>
struct MD5Sum< ::TP2::AnnotatedPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::TP2::AnnotatedPose >::value();
  }
  static const char* value(const ::TP2::AnnotatedPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::TP2::AnnotatedPoseRequest> should match 
// service_traits::DataType< ::TP2::AnnotatedPose > 
template<>
struct DataType< ::TP2::AnnotatedPoseRequest>
{
  static const char* value()
  {
    return DataType< ::TP2::AnnotatedPose >::value();
  }
  static const char* value(const ::TP2::AnnotatedPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::TP2::AnnotatedPoseResponse> should match 
// service_traits::MD5Sum< ::TP2::AnnotatedPose > 
template<>
struct MD5Sum< ::TP2::AnnotatedPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::TP2::AnnotatedPose >::value();
  }
  static const char* value(const ::TP2::AnnotatedPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::TP2::AnnotatedPoseResponse> should match 
// service_traits::DataType< ::TP2::AnnotatedPose > 
template<>
struct DataType< ::TP2::AnnotatedPoseResponse>
{
  static const char* value()
  {
    return DataType< ::TP2::AnnotatedPose >::value();
  }
  static const char* value(const ::TP2::AnnotatedPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TP2_MESSAGE_ANNOTATEDPOSE_H
