// Generated by gencpp from file TP2/my_msg.msg
// DO NOT EDIT!


#ifndef TP2_MESSAGE_MY_MSG_H
#define TP2_MESSAGE_MY_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace TP2
{
template <class ContainerAllocator>
struct my_msg_
{
  typedef my_msg_<ContainerAllocator> Type;

  my_msg_()
    : name()
    , test(false)  {
    }
  my_msg_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , test(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint8_t _test_type;
  _test_type test;





  typedef boost::shared_ptr< ::TP2::my_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::TP2::my_msg_<ContainerAllocator> const> ConstPtr;

}; // struct my_msg_

typedef ::TP2::my_msg_<std::allocator<void> > my_msg;

typedef boost::shared_ptr< ::TP2::my_msg > my_msgPtr;
typedef boost::shared_ptr< ::TP2::my_msg const> my_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::TP2::my_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::TP2::my_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace TP2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'TP2': ['/home/seb/catkin_ws/src/TP2/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::TP2::my_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::TP2::my_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::TP2::my_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::TP2::my_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::TP2::my_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::TP2::my_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::TP2::my_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c57db0100443976166cb61c20bd5aae2";
  }

  static const char* value(const ::TP2::my_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc57db01004439761ULL;
  static const uint64_t static_value2 = 0x66cb61c20bd5aae2ULL;
};

template<class ContainerAllocator>
struct DataType< ::TP2::my_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TP2/my_msg";
  }

  static const char* value(const ::TP2::my_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::TP2::my_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
bool test\n\
";
  }

  static const char* value(const ::TP2::my_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::TP2::my_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.test);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::TP2::my_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::TP2::my_msg_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "test: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.test);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TP2_MESSAGE_MY_MSG_H
