// Generated by gencpp from file TP2/storeCurrentPoseResponse.msg
// DO NOT EDIT!


#ifndef TP2_MESSAGE_STORECURRENTPOSERESPONSE_H
#define TP2_MESSAGE_STORECURRENTPOSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace TP2
{
template <class ContainerAllocator>
struct storeCurrentPoseResponse_
{
  typedef storeCurrentPoseResponse_<ContainerAllocator> Type;

  storeCurrentPoseResponse_()
    : succeed(false)  {
    }
  storeCurrentPoseResponse_(const ContainerAllocator& _alloc)
    : succeed(false)  {
  (void)_alloc;
    }



   typedef uint8_t _succeed_type;
  _succeed_type succeed;





  typedef boost::shared_ptr< ::TP2::storeCurrentPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::TP2::storeCurrentPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct storeCurrentPoseResponse_

typedef ::TP2::storeCurrentPoseResponse_<std::allocator<void> > storeCurrentPoseResponse;

typedef boost::shared_ptr< ::TP2::storeCurrentPoseResponse > storeCurrentPoseResponsePtr;
typedef boost::shared_ptr< ::TP2::storeCurrentPoseResponse const> storeCurrentPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::TP2::storeCurrentPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::TP2::storeCurrentPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace TP2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'TP2': ['/home/seb/catkin_ws/src/TP2/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::TP2::storeCurrentPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::TP2::storeCurrentPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::TP2::storeCurrentPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::TP2::storeCurrentPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::TP2::storeCurrentPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::TP2::storeCurrentPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::TP2::storeCurrentPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d9c3b918a0afafe09791ef8d7853918";
  }

  static const char* value(const ::TP2::storeCurrentPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d9c3b918a0afafeULL;
  static const uint64_t static_value2 = 0x09791ef8d7853918ULL;
};

template<class ContainerAllocator>
struct DataType< ::TP2::storeCurrentPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TP2/storeCurrentPoseResponse";
  }

  static const char* value(const ::TP2::storeCurrentPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::TP2::storeCurrentPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool succeed\n\
\n\
";
  }

  static const char* value(const ::TP2::storeCurrentPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::TP2::storeCurrentPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.succeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct storeCurrentPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::TP2::storeCurrentPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::TP2::storeCurrentPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "succeed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.succeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TP2_MESSAGE_STORECURRENTPOSERESPONSE_H
