// Generated by gencpp from file TP2/storeCurrentPose.msg
// DO NOT EDIT!


#ifndef TP2_MESSAGE_STORECURRENTPOSE_H
#define TP2_MESSAGE_STORECURRENTPOSE_H

#include <ros/service_traits.h>


#include <TP2/storeCurrentPoseRequest.h>
#include <TP2/storeCurrentPoseResponse.h>


namespace TP2
{

struct storeCurrentPose
{

typedef storeCurrentPoseRequest Request;
typedef storeCurrentPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct storeCurrentPose
} // namespace TP2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::TP2::storeCurrentPose > {
  static const char* value()
  {
    return "76cdbda74b9c2ca801810b792eae59ca";
  }

  static const char* value(const ::TP2::storeCurrentPose&) { return value(); }
};

template<>
struct DataType< ::TP2::storeCurrentPose > {
  static const char* value()
  {
    return "TP2/storeCurrentPose";
  }

  static const char* value(const ::TP2::storeCurrentPose&) { return value(); }
};


// service_traits::MD5Sum< ::TP2::storeCurrentPoseRequest> should match 
// service_traits::MD5Sum< ::TP2::storeCurrentPose > 
template<>
struct MD5Sum< ::TP2::storeCurrentPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::TP2::storeCurrentPose >::value();
  }
  static const char* value(const ::TP2::storeCurrentPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::TP2::storeCurrentPoseRequest> should match 
// service_traits::DataType< ::TP2::storeCurrentPose > 
template<>
struct DataType< ::TP2::storeCurrentPoseRequest>
{
  static const char* value()
  {
    return DataType< ::TP2::storeCurrentPose >::value();
  }
  static const char* value(const ::TP2::storeCurrentPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::TP2::storeCurrentPoseResponse> should match 
// service_traits::MD5Sum< ::TP2::storeCurrentPose > 
template<>
struct MD5Sum< ::TP2::storeCurrentPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::TP2::storeCurrentPose >::value();
  }
  static const char* value(const ::TP2::storeCurrentPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::TP2::storeCurrentPoseResponse> should match 
// service_traits::DataType< ::TP2::storeCurrentPose > 
template<>
struct DataType< ::TP2::storeCurrentPoseResponse>
{
  static const char* value()
  {
    return DataType< ::TP2::storeCurrentPose >::value();
  }
  static const char* value(const ::TP2::storeCurrentPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TP2_MESSAGE_STORECURRENTPOSE_H
