// Generated by gencpp from file TP2/storeCurrentPoseRequest.msg
// DO NOT EDIT!


#ifndef TP2_MESSAGE_STORECURRENTPOSEREQUEST_H
#define TP2_MESSAGE_STORECURRENTPOSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace TP2
{
template <class ContainerAllocator>
struct storeCurrentPoseRequest_
{
  typedef storeCurrentPoseRequest_<ContainerAllocator> Type;

  storeCurrentPoseRequest_()
    : azrt()  {
    }
  storeCurrentPoseRequest_(const ContainerAllocator& _alloc)
    : azrt(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _azrt_type;
  _azrt_type azrt;





  typedef boost::shared_ptr< ::TP2::storeCurrentPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::TP2::storeCurrentPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct storeCurrentPoseRequest_

typedef ::TP2::storeCurrentPoseRequest_<std::allocator<void> > storeCurrentPoseRequest;

typedef boost::shared_ptr< ::TP2::storeCurrentPoseRequest > storeCurrentPoseRequestPtr;
typedef boost::shared_ptr< ::TP2::storeCurrentPoseRequest const> storeCurrentPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::TP2::storeCurrentPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::TP2::storeCurrentPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace TP2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'TP2': ['/home/seb/catkin_ws/src/TP2/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::TP2::storeCurrentPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::TP2::storeCurrentPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::TP2::storeCurrentPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::TP2::storeCurrentPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::TP2::storeCurrentPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::TP2::storeCurrentPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::TP2::storeCurrentPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0240f14b6a488cd5ec0fa1bc7d99ee4b";
  }

  static const char* value(const ::TP2::storeCurrentPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0240f14b6a488cd5ULL;
  static const uint64_t static_value2 = 0xec0fa1bc7d99ee4bULL;
};

template<class ContainerAllocator>
struct DataType< ::TP2::storeCurrentPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TP2/storeCurrentPoseRequest";
  }

  static const char* value(const ::TP2::storeCurrentPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::TP2::storeCurrentPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string azrt\n\
";
  }

  static const char* value(const ::TP2::storeCurrentPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::TP2::storeCurrentPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.azrt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct storeCurrentPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::TP2::storeCurrentPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::TP2::storeCurrentPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "azrt: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.azrt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TP2_MESSAGE_STORECURRENTPOSEREQUEST_H
