// Generated by gencpp from file class_6/hourRequest.msg
// DO NOT EDIT!


#ifndef CLASS_6_MESSAGE_HOURREQUEST_H
#define CLASS_6_MESSAGE_HOURREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace class_6
{
template <class ContainerAllocator>
struct hourRequest_
{
  typedef hourRequest_<ContainerAllocator> Type;

  hourRequest_()
    : test(0)  {
    }
  hourRequest_(const ContainerAllocator& _alloc)
    : test(0)  {
  (void)_alloc;
    }



   typedef int64_t _test_type;
  _test_type test;





  typedef boost::shared_ptr< ::class_6::hourRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::class_6::hourRequest_<ContainerAllocator> const> ConstPtr;

}; // struct hourRequest_

typedef ::class_6::hourRequest_<std::allocator<void> > hourRequest;

typedef boost::shared_ptr< ::class_6::hourRequest > hourRequestPtr;
typedef boost::shared_ptr< ::class_6::hourRequest const> hourRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::class_6::hourRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::class_6::hourRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace class_6

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::class_6::hourRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::class_6::hourRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::class_6::hourRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::class_6::hourRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::class_6::hourRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::class_6::hourRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::class_6::hourRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ababf824dbf6c5657a63dc70582ba71";
  }

  static const char* value(const ::class_6::hourRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ababf824dbf6c56ULL;
  static const uint64_t static_value2 = 0x57a63dc70582ba71ULL;
};

template<class ContainerAllocator>
struct DataType< ::class_6::hourRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "class_6/hourRequest";
  }

  static const char* value(const ::class_6::hourRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::class_6::hourRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 test\n\
";
  }

  static const char* value(const ::class_6::hourRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::class_6::hourRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.test);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hourRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::class_6::hourRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::class_6::hourRequest_<ContainerAllocator>& v)
  {
    s << indent << "test: ";
    Printer<int64_t>::stream(s, indent + "  ", v.test);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLASS_6_MESSAGE_HOURREQUEST_H
