// Generated by gencpp from file class_6/hour.msg
// DO NOT EDIT!


#ifndef CLASS_6_MESSAGE_HOUR_H
#define CLASS_6_MESSAGE_HOUR_H

#include <ros/service_traits.h>


#include <class_6/hourRequest.h>
#include <class_6/hourResponse.h>


namespace class_6
{

struct hour
{

typedef hourRequest Request;
typedef hourResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct hour
} // namespace class_6


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::class_6::hour > {
  static const char* value()
  {
    return "909db46b8445c3c9ddb06c5737706275";
  }

  static const char* value(const ::class_6::hour&) { return value(); }
};

template<>
struct DataType< ::class_6::hour > {
  static const char* value()
  {
    return "class_6/hour";
  }

  static const char* value(const ::class_6::hour&) { return value(); }
};


// service_traits::MD5Sum< ::class_6::hourRequest> should match 
// service_traits::MD5Sum< ::class_6::hour > 
template<>
struct MD5Sum< ::class_6::hourRequest>
{
  static const char* value()
  {
    return MD5Sum< ::class_6::hour >::value();
  }
  static const char* value(const ::class_6::hourRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::class_6::hourRequest> should match 
// service_traits::DataType< ::class_6::hour > 
template<>
struct DataType< ::class_6::hourRequest>
{
  static const char* value()
  {
    return DataType< ::class_6::hour >::value();
  }
  static const char* value(const ::class_6::hourRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::class_6::hourResponse> should match 
// service_traits::MD5Sum< ::class_6::hour > 
template<>
struct MD5Sum< ::class_6::hourResponse>
{
  static const char* value()
  {
    return MD5Sum< ::class_6::hour >::value();
  }
  static const char* value(const ::class_6::hourResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::class_6::hourResponse> should match 
// service_traits::DataType< ::class_6::hour > 
template<>
struct DataType< ::class_6::hourResponse>
{
  static const char* value()
  {
    return DataType< ::class_6::hour >::value();
  }
  static const char* value(const ::class_6::hourResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLASS_6_MESSAGE_HOUR_H
